//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.temenos.messagingLayer.pojo package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Ofsml13SecurityContextUserName_QNAME = new QName(
			"http://www.temenos.com/T24/OFSML/130", "userName");
	private final static QName _Ofsml13SecurityContextNickName_QNAME = new QName(
			"http://www.temenos.com/T24/OFSML/130", "nickName");
	private final static QName _Ofsml13SecurityContextCompany_QNAME = new QName("http://www.temenos.com/T24/OFSML/130",
			"company");
	private final static QName _Ofsml13SecurityContextPassword_QNAME = new QName(
			"http://www.temenos.com/T24/OFSML/130", "password");
	private final static QName _Ofsml13FaultDetailsDuplicateReference_QNAME = new QName(
			"http://www.temenos.com/T24/OFSML/130", "duplicateReference");
	private final static QName _Ofsml13TransactionRequestTransactionId_QNAME = new QName(
			"http://www.temenos.com/T24/OFSML/130", "transactionId");
	private final static QName _T24ResponseProcessing_QNAME = new QName("http://www.temenos.com/T24/OFSML/130",
			"responseProcessing");
	private final static QName _T24RequestProcessing_QNAME = new QName("http://www.temenos.com/T24/OFSML/130",
			"requestProcessing");
	private final static QName _T24OfsmlHeader_QNAME = new QName("http://www.temenos.com/T24/OFSML/130", "ofsmlHeader");
	private final static QName _T24RoutineResponseOfsFaultMessage_QNAME = new QName(
			"http://www.temenos.com/T24/OFSML/130", "ofsFaultMessage");
	private final static QName _T24RoutineResponseOfsFaultContext_QNAME = new QName(
			"http://www.temenos.com/T24/OFSML/130", "ofsFaultContext");
	private final static QName _T24RoutineResponseOfsFaultDetails_QNAME = new QName(
			"http://www.temenos.com/T24/OFSML/130", "ofsFaultDetails");
	private final static QName _T24RoutineResponseOfsFaultCode_QNAME = new QName(
			"http://www.temenos.com/T24/OFSML/130", "ofsFaultCode");
	private final static QName _Ofsml13TransactionFailedResponseErrorDescription_QNAME = new QName(
			"http://www.temenos.com/T24/OFSML/130", "errorDescription");
	private final static QName _Ofsml13FaultMessageT24ErrorCode_QNAME = new QName(
			"http://www.temenos.com/T24/OFSML/130", "t24ErrorCode");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * com.temenos.messagingLayer.pojo
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Ofsml13MVField }
	 * 
	 */
	public Ofsml13MVField createOfsml13MVField() {
		return new Ofsml13MVField();
	}

	/**
	 * Create an instance of {@link T24 }
	 * 
	 */
	public T24 createT24() {
		return new T24();
	}

	/**
	 * Create an instance of {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public Ofsml13TransactionNonInputRequest createOfsml13TransactionNonInputRequest() {
		return new Ofsml13TransactionNonInputRequest();
	}

	/**
	 * Create an instance of {@link Ofsml13EnquiryColumnDefinition }
	 * 
	 */
	public Ofsml13EnquiryColumnDefinition createOfsml13EnquiryColumnDefinition() {
		return new Ofsml13EnquiryColumnDefinition();
	}

	/**
	 * Create an instance of {@link Ofsml13OverrideField }
	 * 
	 */
	public Ofsml13OverrideField createOfsml13OverrideField() {
		return new Ofsml13OverrideField();
	}

	/**
	 * Create an instance of {@link Ofsml13StandardEnquiryResponse }
	 * 
	 */
	public Ofsml13StandardEnquiryResponse createOfsml13StandardEnquiryResponse() {
		return new Ofsml13StandardEnquiryResponse();
	}

	/**
	 * Create an instance of {@link Ofsml13IndexRefValue }
	 * 
	 */
	public Ofsml13IndexRefValue createOfsml13IndexRefValue() {
		return new Ofsml13IndexRefValue();
	}

	/**
	 * Create an instance of {@link T24RoutineResponse }
	 * 
	 */
	public T24RoutineResponse createT24RoutineResponse() {
		return new T24RoutineResponse();
	}

	/**
	 * Create an instance of {@link Ofsml13IndexRefGroup }
	 * 
	 */
	public Ofsml13IndexRefGroup createOfsml13IndexRefGroup() {
		return new Ofsml13IndexRefGroup();
	}

	/**
	 * Create an instance of {@link Ofsml13TransactionOfflineResponse }
	 * 
	 */
	public Ofsml13TransactionOfflineResponse createOfsml13TransactionOfflineResponse() {
		return new Ofsml13TransactionOfflineResponse();
	}

	/**
	 * Create an instance of {@link Ofsml13BusinessReport }
	 * 
	 */
	public Ofsml13BusinessReport createOfsml13BusinessReport() {
		return new Ofsml13BusinessReport();
	}

	/**
	 * Create an instance of {@link Ofsml13ResponseProcessing }
	 * 
	 */
	public Ofsml13ResponseProcessing createOfsml13ResponseProcessing() {
		return new Ofsml13ResponseProcessing();
	}

	/**
	 * Create an instance of {@link Ofsml13TransactionProcessedResponse }
	 * 
	 */
	public Ofsml13TransactionProcessedResponse createOfsml13TransactionProcessedResponse() {
		return new Ofsml13TransactionProcessedResponse();
	}

	/**
	 * Create an instance of {@link Ofsml13FaultMessage }
	 * 
	 */
	public Ofsml13FaultMessage createOfsml13FaultMessage() {
		return new Ofsml13FaultMessage();
	}

	/**
	 * Create an instance of {@link Ofsml13Header }
	 * 
	 */
	public Ofsml13Header createOfsml13Header() {
		return new Ofsml13Header();
	}

	/**
	 * Create an instance of {@link Ofsml13FaultDuplicateReference }
	 * 
	 */
	public Ofsml13FaultDuplicateReference createOfsml13FaultDuplicateReference() {
		return new Ofsml13FaultDuplicateReference();
	}

	/**
	 * Create an instance of {@link Ofsml13SecurityContext }
	 * 
	 */
	public Ofsml13SecurityContext createOfsml13SecurityContext() {
		return new Ofsml13SecurityContext();
	}

	/**
	 * Create an instance of {@link Ofsml13TransactionInputRequest }
	 * 
	 */
	public Ofsml13TransactionInputRequest createOfsml13TransactionInputRequest() {
		return new Ofsml13TransactionInputRequest();
	}

	/**
	 * Create an instance of {@link Ofsml13NillableToken }
	 * 
	 */
	public Ofsml13NillableToken createOfsml13NillableToken() {
		return new Ofsml13NillableToken();
	}

	/**
	 * Create an instance of {@link Ofsml13StandardEnquiryRecord }
	 * 
	 */
	public Ofsml13StandardEnquiryRecord createOfsml13StandardEnquiryRecord() {
		return new Ofsml13StandardEnquiryRecord();
	}

	/**
	 * Create an instance of {@link Ofsml13FaultDetails }
	 * 
	 */
	public Ofsml13FaultDetails createOfsml13FaultDetails() {
		return new Ofsml13FaultDetails();
	}

	/**
	 * Create an instance of {@link Ofsml13ServiceResponse }
	 * 
	 */
	public Ofsml13ServiceResponse createOfsml13ServiceResponse() {
		return new Ofsml13ServiceResponse();
	}

	/**
	 * Create an instance of {@link Ofsml13SelectionCriteria }
	 * 
	 */
	public Ofsml13SelectionCriteria createOfsml13SelectionCriteria() {
		return new Ofsml13SelectionCriteria();
	}

	/**
	 * Create an instance of {@link Ofsml13DataSetGroupDefinition }
	 * 
	 */
	public Ofsml13DataSetGroupDefinition createOfsml13DataSetGroupDefinition() {
		return new Ofsml13DataSetGroupDefinition();
	}

	/**
	 * Create an instance of {@link Ofsml13DataSetFieldDefinition }
	 * 
	 */
	public Ofsml13DataSetFieldDefinition createOfsml13DataSetFieldDefinition() {
		return new Ofsml13DataSetFieldDefinition();
	}

	/**
	 * Create an instance of {@link Ofsml13BusinessEvent }
	 * 
	 */
	public Ofsml13BusinessEvent createOfsml13BusinessEvent() {
		return new Ofsml13BusinessEvent();
	}

	/**
	 * Create an instance of {@link Ofsml13ExtendedEnquiryResponse }
	 * 
	 */
	public Ofsml13ExtendedEnquiryResponse createOfsml13ExtendedEnquiryResponse() {
		return new Ofsml13ExtendedEnquiryResponse();
	}

	/**
	 * Create an instance of {@link Ofsml13EnquiryRequest }
	 * 
	 */
	public Ofsml13EnquiryRequest createOfsml13EnquiryRequest() {
		return new Ofsml13EnquiryRequest();
	}

	/**
	 * Create an instance of {@link Ofsml13ServiceSend }
	 * 
	 */
	public Ofsml13ServiceSend createOfsml13ServiceSend() {
		return new Ofsml13ServiceSend();
	}

	/**
	 * Create an instance of {@link Ofsml13TransactionFailedResponse }
	 * 
	 */
	public Ofsml13TransactionFailedResponse createOfsml13TransactionFailedResponse() {
		return new Ofsml13TransactionFailedResponse();
	}

	/**
	 * Create an instance of {@link Ofsml13DataSet }
	 * 
	 */
	public Ofsml13DataSet createOfsml13DataSet() {
		return new Ofsml13DataSet();
	}

	/**
	 * Create an instance of {@link Ofsml13StandardRoutine }
	 * 
	 */
	public Ofsml13StandardRoutine createOfsml13StandardRoutine() {
		return new Ofsml13StandardRoutine();
	}

	/**
	 * Create an instance of {@link Ofsml13DataSetRecord }
	 * 
	 */
	public Ofsml13DataSetRecord createOfsml13DataSetRecord() {
		return new Ofsml13DataSetRecord();
	}

	/**
	 * Create an instance of {@link Ofsml13ServiceRequest }
	 * 
	 */
	public Ofsml13ServiceRequest createOfsml13ServiceRequest() {
		return new Ofsml13ServiceRequest();
	}

	/**
	 * Create an instance of {@link Ofsml13RequestProcessing }
	 * 
	 */
	public Ofsml13RequestProcessing createOfsml13RequestProcessing() {
		return new Ofsml13RequestProcessing();
	}

	/**
	 * Create an instance of {@link Ofsml13XMLRoutine }
	 * 
	 */
	public Ofsml13XMLRoutine createOfsml13XMLRoutine() {
		return new Ofsml13XMLRoutine();
	}

	/**
	 * Create an instance of {@link Ofsml13ErrorField }
	 * 
	 */
	public Ofsml13ErrorField createOfsml13ErrorField() {
		return new Ofsml13ErrorField();
	}

	/**
	 * Create an instance of {@link Ofsml13Fault }
	 * 
	 */
	public Ofsml13Fault createOfsml13Fault() {
		return new Ofsml13Fault();
	}

	/**
	 * Create an instance of {@link Ofsml13IdRefValue }
	 * 
	 */
	public Ofsml13IdRefValue createOfsml13IdRefValue() {
		return new Ofsml13IdRefValue();
	}

	/**
	 * Create an instance of {@link Ofsml13TransactionQueuedResponse }
	 * 
	 */
	public Ofsml13TransactionQueuedResponse createOfsml13TransactionQueuedResponse() {
		return new Ofsml13TransactionQueuedResponse();
	}

	/**
	 * Create an instance of {@link Ofsml13ExtendedEnquiryRecord }
	 * 
	 */
	public Ofsml13ExtendedEnquiryRecord createOfsml13ExtendedEnquiryRecord() {
		return new Ofsml13ExtendedEnquiryRecord();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Ofsml13NillableToken }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "userName", scope = Ofsml13SecurityContext.class)
	public JAXBElement<Ofsml13NillableToken> createOfsml13SecurityContextUserName(Ofsml13NillableToken value) {
		return new JAXBElement<Ofsml13NillableToken>(_Ofsml13SecurityContextUserName_QNAME, Ofsml13NillableToken.class,
				Ofsml13SecurityContext.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "nickName", scope = Ofsml13SecurityContext.class)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	public JAXBElement<String> createOfsml13SecurityContextNickName(String value) {
		return new JAXBElement<String>(_Ofsml13SecurityContextNickName_QNAME, String.class,
				Ofsml13SecurityContext.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Ofsml13NillableToken }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "company", scope = Ofsml13SecurityContext.class)
	public JAXBElement<Ofsml13NillableToken> createOfsml13SecurityContextCompany(Ofsml13NillableToken value) {
		return new JAXBElement<Ofsml13NillableToken>(_Ofsml13SecurityContextCompany_QNAME, Ofsml13NillableToken.class,
				Ofsml13SecurityContext.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Ofsml13NillableToken }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "password", scope = Ofsml13SecurityContext.class)
	public JAXBElement<Ofsml13NillableToken> createOfsml13SecurityContextPassword(Ofsml13NillableToken value) {
		return new JAXBElement<Ofsml13NillableToken>(_Ofsml13SecurityContextPassword_QNAME, Ofsml13NillableToken.class,
				Ofsml13SecurityContext.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Ofsml13FaultDuplicateReference }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "duplicateReference", scope = Ofsml13FaultDetails.class)
	public JAXBElement<Ofsml13FaultDuplicateReference> createOfsml13FaultDetailsDuplicateReference(
			Ofsml13FaultDuplicateReference value) {
		return new JAXBElement<Ofsml13FaultDuplicateReference>(_Ofsml13FaultDetailsDuplicateReference_QNAME,
				Ofsml13FaultDuplicateReference.class, Ofsml13FaultDetails.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Ofsml13NillableToken }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "transactionId", scope = Ofsml13TransactionRequest.class)
	public JAXBElement<Ofsml13NillableToken> createOfsml13TransactionRequestTransactionId(Ofsml13NillableToken value) {
		return new JAXBElement<Ofsml13NillableToken>(_Ofsml13TransactionRequestTransactionId_QNAME,
				Ofsml13NillableToken.class, Ofsml13TransactionRequest.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Ofsml13ResponseProcessing }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "responseProcessing", scope = T24.class)
	public JAXBElement<Ofsml13ResponseProcessing> createT24ResponseProcessing(Ofsml13ResponseProcessing value) {
		return new JAXBElement<Ofsml13ResponseProcessing>(_T24ResponseProcessing_QNAME,
				Ofsml13ResponseProcessing.class, T24.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Ofsml13RequestProcessing }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "requestProcessing", scope = T24.class)
	public JAXBElement<Ofsml13RequestProcessing> createT24RequestProcessing(Ofsml13RequestProcessing value) {
		return new JAXBElement<Ofsml13RequestProcessing>(_T24RequestProcessing_QNAME, Ofsml13RequestProcessing.class,
				T24.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Ofsml13Header }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "ofsmlHeader", scope = T24.class)
	public JAXBElement<Ofsml13Header> createT24OfsmlHeader(Ofsml13Header value) {
		return new JAXBElement<Ofsml13Header>(_T24OfsmlHeader_QNAME, Ofsml13Header.class, T24.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Ofsml13FaultMessage }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "ofsFaultMessage", scope = T24RoutineResponse.class)
	public JAXBElement<Ofsml13FaultMessage> createT24RoutineResponseOfsFaultMessage(Ofsml13FaultMessage value) {
		return new JAXBElement<Ofsml13FaultMessage>(_T24RoutineResponseOfsFaultMessage_QNAME,
				Ofsml13FaultMessage.class, T24RoutineResponse.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "ofsFaultContext", scope = T24RoutineResponse.class)
	public JAXBElement<String> createT24RoutineResponseOfsFaultContext(String value) {
		return new JAXBElement<String>(_T24RoutineResponseOfsFaultContext_QNAME, String.class,
				T24RoutineResponse.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Ofsml13FaultDetails }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "ofsFaultDetails", scope = T24RoutineResponse.class)
	public JAXBElement<Ofsml13FaultDetails> createT24RoutineResponseOfsFaultDetails(Ofsml13FaultDetails value) {
		return new JAXBElement<Ofsml13FaultDetails>(_T24RoutineResponseOfsFaultDetails_QNAME,
				Ofsml13FaultDetails.class, T24RoutineResponse.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Ofsml13FaultCode }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "ofsFaultCode", scope = T24RoutineResponse.class)
	public JAXBElement<Ofsml13FaultCode> createT24RoutineResponseOfsFaultCode(Ofsml13FaultCode value) {
		return new JAXBElement<Ofsml13FaultCode>(_T24RoutineResponseOfsFaultCode_QNAME, Ofsml13FaultCode.class,
				T24RoutineResponse.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "errorDescription", scope = Ofsml13TransactionFailedResponse.class)
	public JAXBElement<String> createOfsml13TransactionFailedResponseErrorDescription(String value) {
		return new JAXBElement<String>(_Ofsml13TransactionFailedResponseErrorDescription_QNAME, String.class,
				Ofsml13TransactionFailedResponse.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Ofsml13NillableToken }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.temenos.com/T24/OFSML/130", name = "t24ErrorCode", scope = Ofsml13FaultMessage.class)
	public JAXBElement<Ofsml13NillableToken> createOfsml13FaultMessageT24ErrorCode(Ofsml13NillableToken value) {
		return new JAXBElement<Ofsml13NillableToken>(_Ofsml13FaultMessageT24ErrorCode_QNAME,
				Ofsml13NillableToken.class, Ofsml13FaultMessage.class, value);
	}

}
