//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Denotes a failure to process the transaction due to a business validation failure. The original
 * transaction request is returned, along with the fields in error. If the GTS Control is configured (in T24) to
 * accept failed transactions to the 'hold' work queue, the held attribute is set to true and the associated transaction
 * ID reserved by T24 is returned in the optional transactionId element.
 * 
 * 
 * <p>
 * Java class for ofsml13TransactionFailedResponse complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13TransactionFailedResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.temenos.com/T24/OFSML/130}ofsml13TransactionResponse">
 *       &lt;sequence>
 *         &lt;element name="errorDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="error" type="{http://www.temenos.com/T24/OFSML/130}ofsml13ErrorField" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://www.temenos.com/T24/OFSML/130}ofsml13TransactionRequestGroup"/>
 *       &lt;/sequence>
 *       &lt;attribute name="held" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13TransactionFailedResponse", propOrder = { "errorDescription", "error", "ofsTransactionInput",
		"ofsTransactionAuthorise", "ofsTransactionSee", "ofsTransactionReverse", "ofsTransactionDelete" })
public class Ofsml13TransactionFailedResponse extends Ofsml13TransactionResponse {

	@XmlElementRef(name = "errorDescription", namespace = "http://www.temenos.com/T24/OFSML/130", type = JAXBElement.class)
	protected JAXBElement<String> errorDescription;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected List<Ofsml13ErrorField> error;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionInputRequest ofsTransactionInput;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionNonInputRequest ofsTransactionAuthorise;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionNonInputRequest ofsTransactionSee;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionNonInputRequest ofsTransactionReverse;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionNonInputRequest ofsTransactionDelete;
	@XmlAttribute
	protected Boolean held;

	/**
	 * Gets the value of the errorDescription property.
	 * 
	 * @return
	 *         possible object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public JAXBElement<String> getErrorDescription() {
		return errorDescription;
	}

	/**
	 * Sets the value of the errorDescription property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	public void setErrorDescription(JAXBElement<String> value) {
		this.errorDescription = ((JAXBElement<String>) value);
	}

	/**
	 * Gets the value of the error property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the error property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getError().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Ofsml13ErrorField }
	 * 
	 * 
	 */
	public List<Ofsml13ErrorField> getError() {
		if (error == null) {
			error = new ArrayList<Ofsml13ErrorField>();
		}
		return this.error;
	}

	/**
	 * Gets the value of the ofsTransactionInput property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionInputRequest }
	 * 
	 */
	public Ofsml13TransactionInputRequest getOfsTransactionInput() {
		return ofsTransactionInput;
	}

	/**
	 * Sets the value of the ofsTransactionInput property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionInputRequest }
	 * 
	 */
	public void setOfsTransactionInput(Ofsml13TransactionInputRequest value) {
		this.ofsTransactionInput = value;
	}

	/**
	 * Gets the value of the ofsTransactionAuthorise property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public Ofsml13TransactionNonInputRequest getOfsTransactionAuthorise() {
		return ofsTransactionAuthorise;
	}

	/**
	 * Sets the value of the ofsTransactionAuthorise property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public void setOfsTransactionAuthorise(Ofsml13TransactionNonInputRequest value) {
		this.ofsTransactionAuthorise = value;
	}

	/**
	 * Gets the value of the ofsTransactionSee property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public Ofsml13TransactionNonInputRequest getOfsTransactionSee() {
		return ofsTransactionSee;
	}

	/**
	 * Sets the value of the ofsTransactionSee property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public void setOfsTransactionSee(Ofsml13TransactionNonInputRequest value) {
		this.ofsTransactionSee = value;
	}

	/**
	 * Gets the value of the ofsTransactionReverse property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public Ofsml13TransactionNonInputRequest getOfsTransactionReverse() {
		return ofsTransactionReverse;
	}

	/**
	 * Sets the value of the ofsTransactionReverse property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public void setOfsTransactionReverse(Ofsml13TransactionNonInputRequest value) {
		this.ofsTransactionReverse = value;
	}

	/**
	 * Gets the value of the ofsTransactionDelete property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public Ofsml13TransactionNonInputRequest getOfsTransactionDelete() {
		return ofsTransactionDelete;
	}

	/**
	 * Sets the value of the ofsTransactionDelete property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public void setOfsTransactionDelete(Ofsml13TransactionNonInputRequest value) {
		this.ofsTransactionDelete = value;
	}

	/**
	 * Gets the value of the held property.
	 * 
	 * @return
	 *         possible object is {@link Boolean }
	 * 
	 */
	public boolean isHeld() {
		if (held == null) {
			return false;
		} else {
			return held;
		}
	}

	/**
	 * Sets the value of the held property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setHeld(Boolean value) {
		this.held = value;
	}

}
