//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * <p>
 * Java class for ofsml13TranslatorContext.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="ofsml13TranslatorContext">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="LOCAL"/>
 *     &lt;enumeration value="DEFERRED"/>
 *     &lt;enumeration value="HTML-RENDER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum Ofsml13TranslatorContext {

	DEFERRED("DEFERRED"), @XmlEnumValue("HTML-RENDER")
	HTML_RENDER("HTML-RENDER"), LOCAL("LOCAL");
	private final String value;

	Ofsml13TranslatorContext(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static Ofsml13TranslatorContext fromValue(String v) {
		for (Ofsml13TranslatorContext c : Ofsml13TranslatorContext.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v.toString());
	}

}
