//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * <p>
 * Java class for ofsml13ProcessingStatus.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="ofsml13ProcessingStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="OK"/>
 *     &lt;enumeration value="NOT-AUTHORISED"/>
 *     &lt;enumeration value="ON-HOLD"/>
 *     &lt;enumeration value="MATURED"/>
 *     &lt;enumeration value="PARTIAL-INPUT"/>
 *     &lt;enumeration value="QUEUED"/>
 *     &lt;enumeration value="NOT-QUEUED"/>
 *     &lt;enumeration value="REVERSED"/>
 *     &lt;enumeration value="DELETED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum Ofsml13ProcessingStatus {

	DELETED("DELETED"), MATURED("MATURED"), @XmlEnumValue("NOT-AUTHORISED")
	NOT_AUTHORISED("NOT-AUTHORISED"), @XmlEnumValue("NOT-QUEUED")
	NOT_QUEUED("NOT-QUEUED"), OK("OK"), @XmlEnumValue("ON-HOLD")
	ON_HOLD("ON-HOLD"), @XmlEnumValue("PARTIAL-INPUT")
	PARTIAL_INPUT("PARTIAL-INPUT"), QUEUED("QUEUED"), REVERSED("REVERSED");
	private final String value;

	Ofsml13ProcessingStatus(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static Ofsml13ProcessingStatus fromValue(String v) {
		for (Ofsml13ProcessingStatus c : Ofsml13ProcessingStatus.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v.toString());
	}

}
