//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Abstract type for all transaction requests.
 * 
 * 
 * <p>
 * Java class for ofsml13TransactionRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13TransactionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.temenos.com/T24/OFSML/130}ofsml13Transaction">
 *       &lt;sequence>
 *         &lt;element name="transactionId" type="{http://www.temenos.com/T24/OFSML/130}ofsml13NillableToken" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operation" type="{http://www.temenos.com/T24/OFSML/130}ofsml13OperationCode" default="PROCESS" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13TransactionRequest", propOrder = { "transactionId" })
public abstract class Ofsml13TransactionRequest extends Ofsml13Transaction {

	@XmlElementRef(name = "transactionId", namespace = "http://www.temenos.com/T24/OFSML/130", type = JAXBElement.class)
	protected JAXBElement<Ofsml13NillableToken> transactionId;
	@XmlAttribute
	protected Ofsml13OperationCode operation;

	/**
	 * Gets the value of the transactionId property.
	 * 
	 * @return
	 *         possible object is {@link JAXBElement }{@code <}{@link Ofsml13NillableToken }{@code >}
	 * 
	 */
	public JAXBElement<Ofsml13NillableToken> getTransactionId() {
		return transactionId;
	}

	/**
	 * Sets the value of the transactionId property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link Ofsml13NillableToken }{@code >}
	 * 
	 */
	public void setTransactionId(JAXBElement<Ofsml13NillableToken> value) {
		this.transactionId = ((JAXBElement<Ofsml13NillableToken>) value);
	}

	/**
	 * Gets the value of the operation property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13OperationCode }
	 * 
	 */
	public Ofsml13OperationCode getOperation() {
		if (operation == null) {
			return Ofsml13OperationCode.PROCESS;
		} else {
			return operation;
		}
	}

	/**
	 * Sets the value of the operation property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13OperationCode }
	 * 
	 */
	public void setOperation(Ofsml13OperationCode value) {
		this.operation = value;
	}

}
