//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Abstract type for all transaction responses.
 * 
 * 
 * <p>
 * Java class for ofsml13TransactionResponse complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13TransactionResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.temenos.com/T24/OFSML/130}ofsml13Transaction">
 *       &lt;sequence>
 *         &lt;element name="transactionId" type="{http://www.temenos.com/T24/OFSML/130}ofsml13NillableToken"/>
 *       &lt;/sequence>
 *       &lt;attribute name="function" use="required" type="{http://www.temenos.com/T24/OFSML/130}ofsml13FunctionCode" />
 *       &lt;attribute name="operation" use="required" type="{http://www.temenos.com/T24/OFSML/130}ofsml13OperationCode" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13TransactionResponse", propOrder = { "transactionId" })
public abstract class Ofsml13TransactionResponse extends Ofsml13Transaction {

	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130", nillable = true)
	protected Ofsml13NillableToken transactionId;
	@XmlAttribute(required = true)
	protected Ofsml13FunctionCode function;
	@XmlAttribute(required = true)
	protected Ofsml13OperationCode operation;

	/**
	 * Gets the value of the transactionId property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13NillableToken }
	 * 
	 */
	public Ofsml13NillableToken getTransactionId() {
		return transactionId;
	}

	/**
	 * Sets the value of the transactionId property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13NillableToken }
	 * 
	 */
	public void setTransactionId(Ofsml13NillableToken value) {
		this.transactionId = value;
	}

	/**
	 * Gets the value of the function property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13FunctionCode }
	 * 
	 */
	public Ofsml13FunctionCode getFunction() {
		return function;
	}

	/**
	 * Sets the value of the function property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13FunctionCode }
	 * 
	 */
	public void setFunction(Ofsml13FunctionCode value) {
		this.function = value;
	}

	/**
	 * Gets the value of the operation property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13OperationCode }
	 * 
	 */
	public Ofsml13OperationCode getOperation() {
		return operation;
	}

	/**
	 * Sets the value of the operation property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13OperationCode }
	 * 
	 */
	public void setOperation(Ofsml13OperationCode value) {
		this.operation = value;
	}

}
