//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Denotes a de-normalised (extended) enquiry service request.
 * 
 * 
 * <p>
 * Java class for ofsml13ExtendedEnquiryResponse complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13ExtendedEnquiryResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.temenos.com/T24/OFSML/130}ofsml13EnquiryResponse">
 *       &lt;sequence>
 *         &lt;element name="enquiryRecord" type="{http://www.temenos.com/T24/OFSML/130}ofsml13ExtendedEnquiryRecord" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13ExtendedEnquiryResponse", propOrder = { "enquiryRecord" })
public class Ofsml13ExtendedEnquiryResponse extends Ofsml13EnquiryResponse {

	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected List<Ofsml13ExtendedEnquiryRecord> enquiryRecord;

	/**
	 * Gets the value of the enquiryRecord property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the enquiryRecord property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getEnquiryRecord().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Ofsml13ExtendedEnquiryRecord }
	 * 
	 * 
	 */
	public List<Ofsml13ExtendedEnquiryRecord> getEnquiryRecord() {
		if (enquiryRecord == null) {
			enquiryRecord = new ArrayList<Ofsml13ExtendedEnquiryRecord>();
		}
		return this.enquiryRecord;
	}

}
