//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Where a (technical) failure to process a request has occurred, the fault message may be returned to help determine
 * the cause.
 * Note that the fault message may contain both a text error message, plus an optional (tagged) T24 error code (for
 * extensibility).
 * 
 * 
 * <p>
 * Java class for ofsml13FaultMessage complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13FaultMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="t24ErrorCode" type="{http://www.temenos.com/T24/OFSML/130}ofsml13NillableToken" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13FaultMessage", propOrder = { "content" })
public class Ofsml13FaultMessage {

	@XmlElementRef(name = "t24ErrorCode", namespace = "http://www.temenos.com/T24/OFSML/130", type = JAXBElement.class)
	@XmlMixed
	protected List<Serializable> content;

	/**
	 * 
	 * Where a (technical) failure to process a request has occurred, the fault message may be returned to help
	 * determine the cause.
	 * Note that the fault message may contain both a text error message, plus an optional (tagged) T24 error code (for
	 * extensibility).
	 * Gets the value of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link Ofsml13NillableToken }
	 * {@code >} {@link String }
	 * 
	 * 
	 */
	public List<Serializable> getContent() {
		if (content == null) {
			content = new ArrayList<Serializable>();
		}
		return this.content;
	}

}
