//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 * Denotes an off-line queued transaction response (accepted for processing at the start of the next
 * business cycle). An off-line reference is returned. Where a transaction id was specified, this is returned also
 * (otherwise a nil transactionId element is returned). This option is configurable in T24.
 * 
 * 
 * <p>
 * Java class for ofsml13TransactionQueuedResponse complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13TransactionQueuedResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.temenos.com/T24/OFSML/130}ofsml13TransactionResponse">
 *       &lt;sequence>
 *         &lt;element name="offlineReference" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="field" type="{http://www.temenos.com/T24/OFSML/130}ofsml13MVField" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13TransactionQueuedResponse", propOrder = { "offlineReference", "field" })
public class Ofsml13TransactionQueuedResponse extends Ofsml13TransactionResponse {

	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String offlineReference;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected List<Ofsml13MVField> field;

	/**
	 * Gets the value of the offlineReference property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getOfflineReference() {
		return offlineReference;
	}

	/**
	 * Sets the value of the offlineReference property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOfflineReference(String value) {
		this.offlineReference = value;
	}

	/**
	 * Gets the value of the field property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the field property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getField().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Ofsml13MVField }
	 * 
	 * 
	 */
	public List<Ofsml13MVField> getField() {
		if (field == null) {
			field = new ArrayList<Ofsml13MVField>();
		}
		return this.field;
	}

}
