//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import javax.xml.bind.annotation.XmlEnum;

/**
 * <p>
 * Java class for ofsml13OperationCode.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="ofsml13OperationCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="PROCESS"/>
 *     &lt;enumeration value="VALIDATE"/>
 *     &lt;enumeration value="BUILD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum Ofsml13OperationCode {

	BUILD, PROCESS, VALIDATE;

	public String value() {
		return name();
	}

	public Ofsml13OperationCode fromValue(String v) {
		return valueOf(v);
	}

}
