//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * A service response forms the response to a corresponding service request. For each specific type of request
 * made by the caller (defined by the ofsmlServiceRequest model group), there will be a corresponding 'response' in the
 * ofsmlServiceResponse. Any business validation errors that occur during the processing of a request are returned in
 * the
 * body of the corresponding response element. Any request that could not be (or was not) processed due to a technical
 * error is returned as an ofsFault. OFSML 1.1 model groups are NOT permitted.
 * 
 * 
 * <p>
 * Java class for ofsml13ServiceResponse complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13ServiceResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ofsTransactionProcessed" type="{http://www.temenos.com/T24/OFSML/130}ofsml13TransactionProcessedResponse"/>
 *         &lt;element name="ofsTransactionQueued" type="{http://www.temenos.com/T24/OFSML/130}ofsml13TransactionQueuedResponse"/>
 *         &lt;element name="ofsTransactionOffline" type="{http://www.temenos.com/T24/OFSML/130}ofsml13TransactionOfflineResponse"/>
 *         &lt;element name="ofsTransactionFailed" type="{http://www.temenos.com/T24/OFSML/130}ofsml13TransactionFailedResponse"/>
 *         &lt;element name="ofsStandardEnquiry" type="{http://www.temenos.com/T24/OFSML/130}ofsml13StandardEnquiryResponse"/>
 *         &lt;element name="ofsExtendedEnquiry" type="{http://www.temenos.com/T24/OFSML/130}ofsml13ExtendedEnquiryResponse"/>
 *         &lt;element name="ofsStandardRoutine" type="{http://www.temenos.com/T24/OFSML/130}ofsml13StandardRoutine"/>
 *         &lt;element name="ofsXMLRoutine" type="{http://www.temenos.com/T24/OFSML/130}ofsml13XMLRoutine"/>
 *         &lt;element name="ofsFault" type="{http://www.temenos.com/T24/OFSML/130}ofsml13Fault"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13ServiceResponse", propOrder = { "ofsTransactionProcessed", "ofsTransactionQueued",
		"ofsTransactionOffline", "ofsTransactionFailed", "ofsStandardEnquiry", "ofsExtendedEnquiry",
		"ofsStandardRoutine", "ofsXMLRoutine", "ofsFault" })
public class Ofsml13ServiceResponse {

	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionProcessedResponse ofsTransactionProcessed;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionQueuedResponse ofsTransactionQueued;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionOfflineResponse ofsTransactionOffline;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionFailedResponse ofsTransactionFailed;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13StandardEnquiryResponse ofsStandardEnquiry;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13ExtendedEnquiryResponse ofsExtendedEnquiry;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13StandardRoutine ofsStandardRoutine;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13XMLRoutine ofsXMLRoutine;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13Fault ofsFault;

	/**
	 * Gets the value of the ofsTransactionProcessed property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionProcessedResponse }
	 * 
	 */
	public Ofsml13TransactionProcessedResponse getOfsTransactionProcessed() {
		return ofsTransactionProcessed;
	}

	/**
	 * Sets the value of the ofsTransactionProcessed property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionProcessedResponse }
	 * 
	 */
	public void setOfsTransactionProcessed(Ofsml13TransactionProcessedResponse value) {
		this.ofsTransactionProcessed = value;
	}

	/**
	 * Gets the value of the ofsTransactionQueued property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionQueuedResponse }
	 * 
	 */
	public Ofsml13TransactionQueuedResponse getOfsTransactionQueued() {
		return ofsTransactionQueued;
	}

	/**
	 * Sets the value of the ofsTransactionQueued property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionQueuedResponse }
	 * 
	 */
	public void setOfsTransactionQueued(Ofsml13TransactionQueuedResponse value) {
		this.ofsTransactionQueued = value;
	}

	/**
	 * Gets the value of the ofsTransactionOffline property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionOfflineResponse }
	 * 
	 */
	public Ofsml13TransactionOfflineResponse getOfsTransactionOffline() {
		return ofsTransactionOffline;
	}

	/**
	 * Sets the value of the ofsTransactionOffline property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionOfflineResponse }
	 * 
	 */
	public void setOfsTransactionOffline(Ofsml13TransactionOfflineResponse value) {
		this.ofsTransactionOffline = value;
	}

	/**
	 * Gets the value of the ofsTransactionFailed property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionFailedResponse }
	 * 
	 */
	public Ofsml13TransactionFailedResponse getOfsTransactionFailed() {
		return ofsTransactionFailed;
	}

	/**
	 * Sets the value of the ofsTransactionFailed property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionFailedResponse }
	 * 
	 */
	public void setOfsTransactionFailed(Ofsml13TransactionFailedResponse value) {
		this.ofsTransactionFailed = value;
	}

	/**
	 * Gets the value of the ofsStandardEnquiry property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13StandardEnquiryResponse }
	 * 
	 */
	public Ofsml13StandardEnquiryResponse getOfsStandardEnquiry() {
		return ofsStandardEnquiry;
	}

	/**
	 * Sets the value of the ofsStandardEnquiry property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13StandardEnquiryResponse }
	 * 
	 */
	public void setOfsStandardEnquiry(Ofsml13StandardEnquiryResponse value) {
		this.ofsStandardEnquiry = value;
	}

	/**
	 * Gets the value of the ofsExtendedEnquiry property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13ExtendedEnquiryResponse }
	 * 
	 */
	public Ofsml13ExtendedEnquiryResponse getOfsExtendedEnquiry() {
		return ofsExtendedEnquiry;
	}

	/**
	 * Sets the value of the ofsExtendedEnquiry property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13ExtendedEnquiryResponse }
	 * 
	 */
	public void setOfsExtendedEnquiry(Ofsml13ExtendedEnquiryResponse value) {
		this.ofsExtendedEnquiry = value;
	}

	/**
	 * Gets the value of the ofsStandardRoutine property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13StandardRoutine }
	 * 
	 */
	public Ofsml13StandardRoutine getOfsStandardRoutine() {
		return ofsStandardRoutine;
	}

	/**
	 * Sets the value of the ofsStandardRoutine property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13StandardRoutine }
	 * 
	 */
	public void setOfsStandardRoutine(Ofsml13StandardRoutine value) {
		this.ofsStandardRoutine = value;
	}

	/**
	 * Gets the value of the ofsXMLRoutine property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13XMLRoutine }
	 * 
	 */
	public Ofsml13XMLRoutine getOfsXMLRoutine() {
		return ofsXMLRoutine;
	}

	/**
	 * Sets the value of the ofsXMLRoutine property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13XMLRoutine }
	 * 
	 */
	public void setOfsXMLRoutine(Ofsml13XMLRoutine value) {
		this.ofsXMLRoutine = value;
	}

	/**
	 * Gets the value of the ofsFault property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13Fault }
	 * 
	 */
	public Ofsml13Fault getOfsFault() {
		return ofsFault;
	}

	/**
	 * Sets the value of the ofsFault property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13Fault }
	 * 
	 */
	public void setOfsFault(Ofsml13Fault value) {
		this.ofsFault = value;
	}

}
