//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * A single record in a report from T24.
 * 
 * 
 * <p>
 * Java class for ofsml13DataSetRecord complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13DataSetRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="field" type="{http://www.temenos.com/T24/OFSML/130}ofsml13IndexRefValue"/>
 *         &lt;element name="group" type="{http://www.temenos.com/T24/OFSML/130}ofsml13IndexRefGroup"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13DataSetRecord", propOrder = { "fieldOrGroup" })
public class Ofsml13DataSetRecord {

	@XmlElements({
			@XmlElement(name = "group", namespace = "http://www.temenos.com/T24/OFSML/130", type = Ofsml13IndexRefGroup.class),
			@XmlElement(name = "field", namespace = "http://www.temenos.com/T24/OFSML/130", type = Ofsml13IndexRefValue.class) })
	protected List<Object> fieldOrGroup;

	/**
	 * Gets the value of the fieldOrGroup property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the fieldOrGroup property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFieldOrGroup().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Ofsml13IndexRefGroup }
	 * {@link Ofsml13IndexRefValue }
	 * 
	 * 
	 */
	public List<Object> getFieldOrGroup() {
		if (fieldOrGroup == null) {
			fieldOrGroup = new ArrayList<Object>();
		}
		return this.fieldOrGroup;
	}

}
