//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 * Defines a single named data set.
 * 
 * 
 * <p>
 * Java class for ofsml13DataSet complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13DataSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="fieldDefinition" type="{http://www.temenos.com/T24/OFSML/130}ofsml13DataSetFieldDefinition"/>
 *           &lt;element name="groupDefinition" type="{http://www.temenos.com/T24/OFSML/130}ofsml13DataSetGroupDefinition"/>
 *         &lt;/choice>
 *         &lt;element name="record" type="{http://www.temenos.com/T24/OFSML/130}ofsml13DataSetRecord" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13DataSet", propOrder = { "fieldDefinitionOrGroupDefinition", "record" })
public class Ofsml13DataSet {

	@XmlElements({
			@XmlElement(name = "groupDefinition", namespace = "http://www.temenos.com/T24/OFSML/130", type = Ofsml13DataSetGroupDefinition.class),
			@XmlElement(name = "fieldDefinition", namespace = "http://www.temenos.com/T24/OFSML/130", type = Ofsml13DataSetFieldDefinition.class) })
	protected List<Object> fieldDefinitionOrGroupDefinition;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected List<Ofsml13DataSetRecord> record;
	@XmlAttribute(required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String name;

	/**
	 * Gets the value of the fieldDefinitionOrGroupDefinition property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the fieldDefinitionOrGroupDefinition property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFieldDefinitionOrGroupDefinition().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Ofsml13DataSetGroupDefinition }
	 * {@link Ofsml13DataSetFieldDefinition }
	 * 
	 * 
	 */
	public List<Object> getFieldDefinitionOrGroupDefinition() {
		if (fieldDefinitionOrGroupDefinition == null) {
			fieldDefinitionOrGroupDefinition = new ArrayList<Object>();
		}
		return this.fieldDefinitionOrGroupDefinition;
	}

	/**
	 * Gets the value of the record property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the record property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRecord().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Ofsml13DataSetRecord }
	 * 
	 * 
	 */
	public List<Ofsml13DataSetRecord> getRecord() {
		if (record == null) {
			record = new ArrayList<Ofsml13DataSetRecord>();
		}
		return this.record;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

}
