//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
/**
 * 
 * An OFSML (standard) routine request or response, based on a custom routine in the T24 environment where the routine
 * is producing
 * string-based output. The type (T24 name) of the routine is denoted by the attributes. No validation of the input or
 * output is performed,
 * but forbidden characters are replaced on the output with XML-compliant escape sequences.
 * 
 * 
 * <p>
 * Java class for ofsml13StandardRoutine complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13StandardRoutine">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.temenos.com/T24/OFSML/130}ofsml13Routine">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13StandardRoutine")
public class Ofsml13StandardRoutine extends Ofsml13Routine {

}
