//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 * A selection criteria provided by the caller when requesting information from T24 via an enquiry. Uses a
 * Reverse-Polish style argument order.
 * 
 * 
 * <p>
 * Java class for ofsml13SelectionCriteria complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13SelectionCriteria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operand" use="required" type="{http://www.temenos.com/T24/OFSML/130}ofsml13SelectionOperand" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13SelectionCriteria", propOrder = { "fieldName", "value" })
public class Ofsml13SelectionCriteria {

	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String fieldName;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected List<String> value;
	@XmlAttribute(required = true)
	protected Ofsml13SelectionOperand operand;

	/**
	 * Gets the value of the fieldName property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getFieldName() {
		return fieldName;
	}

	/**
	 * Sets the value of the fieldName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFieldName(String value) {
		this.fieldName = value;
	}

	/**
	 * Gets the value of the value property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the value property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getValue().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getValue() {
		if (value == null) {
			value = new ArrayList<String>();
		}
		return this.value;
	}

	/**
	 * Gets the value of the operand property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13SelectionOperand }
	 * 
	 */
	public Ofsml13SelectionOperand getOperand() {
		return operand;
	}

	/**
	 * Sets the value of the operand property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13SelectionOperand }
	 * 
	 */
	public void setOperand(Ofsml13SelectionOperand value) {
		this.operand = value;
	}

}
