//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * OFSML 1.2+ model group. The corresponding OFSML 1.1 model group definition is no longer supported.
 * Where some form of processing is requested on the response (message), the caller may specify such additional
 * processing
 * of the message via a W3C compliant XSLT that may be managed locally or deferred. The type of processing is specified
 * via the translatorContext element and the translation XSLT by the responseTranslator element. Where processing is
 * requested,
 * this is performed by the TOCF.
 * 
 * 
 * <p>
 * Java class for ofsml13ResponseProcessing complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13ResponseProcessing">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="translatorContext" type="{http://www.temenos.com/T24/OFSML/130}ofsml13TranslatorContext"/>
 *         &lt;element name="responseTranslator" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13ResponseProcessing", propOrder = {

})
public class Ofsml13ResponseProcessing {

	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TranslatorContext translatorContext;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected String responseTranslator;

	/**
	 * Gets the value of the translatorContext property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TranslatorContext }
	 * 
	 */
	public Ofsml13TranslatorContext getTranslatorContext() {
		return translatorContext;
	}

	/**
	 * Sets the value of the translatorContext property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TranslatorContext }
	 * 
	 */
	public void setTranslatorContext(Ofsml13TranslatorContext value) {
		this.translatorContext = value;
	}

	/**
	 * Gets the value of the responseTranslator property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getResponseTranslator() {
		return responseTranslator;
	}

	/**
	 * Sets the value of the responseTranslator property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResponseTranslator(String value) {
		this.responseTranslator = value;
	}

}
