//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Denotes a transaction input service request.
 * 
 * 
 * <p>
 * Java class for ofsml13TransactionInputRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13TransactionInputRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.temenos.com/T24/OFSML/130}ofsml13TransactionRequest">
 *       &lt;sequence>
 *         &lt;element name="field" type="{http://www.temenos.com/T24/OFSML/130}ofsml13MVField" maxOccurs="unbounded"/>
 *         &lt;element name="auxField" type="{http://www.temenos.com/T24/OFSML/130}ofsml13MVField" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13TransactionInputRequest", propOrder = { "field", "auxField" })
public class Ofsml13TransactionInputRequest extends Ofsml13TransactionRequest {

	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130", nillable = true)
	protected List<Ofsml13MVField> field;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130", nillable = true)
	protected List<Ofsml13MVField> auxField;

	/**
	 * Gets the value of the field property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the field property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getField().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Ofsml13MVField }
	 * 
	 * 
	 */
	public List<Ofsml13MVField> getField() {
		if (field == null) {
			field = new ArrayList<Ofsml13MVField>();
		}
		return this.field;
	}

	/**
	 * Gets the value of the auxField property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the auxField property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAuxField().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Ofsml13MVField }
	 * 
	 * 
	 */
	public List<Ofsml13MVField> getAuxField() {
		if (auxField == null) {
			auxField = new ArrayList<Ofsml13MVField>();
		}
		return this.auxField;
	}

}
