//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * A repeating group definition in a data set.
 * 
 * 
 * <p>
 * Java class for ofsml13DataSetGroupDefinition complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13DataSetGroupDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="memberDefinition" type="{http://www.temenos.com/T24/OFSML/130}ofsml13DataSetFieldDefinition" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="noOfMembers" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13DataSetGroupDefinition", propOrder = { "memberDefinition" })
public class Ofsml13DataSetGroupDefinition {

	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected List<Ofsml13DataSetFieldDefinition> memberDefinition;
	@XmlAttribute(required = true)
	protected BigInteger index;
	@XmlAttribute(required = true)
	protected BigInteger noOfMembers;

	/**
	 * Gets the value of the memberDefinition property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the memberDefinition property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMemberDefinition().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Ofsml13DataSetFieldDefinition }
	 * 
	 * 
	 */
	public List<Ofsml13DataSetFieldDefinition> getMemberDefinition() {
		if (memberDefinition == null) {
			memberDefinition = new ArrayList<Ofsml13DataSetFieldDefinition>();
		}
		return this.memberDefinition;
	}

	/**
	 * Gets the value of the index property.
	 * 
	 * @return
	 *         possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getIndex() {
		return index;
	}

	/**
	 * Sets the value of the index property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setIndex(BigInteger value) {
		this.index = value;
	}

	/**
	 * Gets the value of the noOfMembers property.
	 * 
	 * @return
	 *         possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNoOfMembers() {
		return noOfMembers;
	}

	/**
	 * Sets the value of the noOfMembers property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setNoOfMembers(BigInteger value) {
		this.noOfMembers = value;
	}

}
