//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlType;

import org.w3c.dom.Element;

/**
 * 
 * Denotes an XML custom routine service request or response, based on a custom routine in the T24 environment where the
 * routine is directly
 * accepting XML as input and producing an XML output compliant with the T24RoutineResponse element definition.
 * The type (T24 name) of the routine is denoted by the attributes. Where an external element definition is utilised,
 * XML parsing errors
 * will cause an ofsFault element to be returned (XML validation processing is set to strict; a content model must be
 * supplied).
 * 
 * 
 * <p>
 * Java class for ofsml13XMLRoutine complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13XMLRoutine">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.temenos.com/T24/OFSML/130}ofsml13Routine">
 *       &lt;sequence>
 *         &lt;any/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13XMLRoutine", propOrder = { "any" })
public class Ofsml13XMLRoutine extends Ofsml13Routine {

	@XmlAnyElement(lax = true)
	protected Object any;

	/**
	 * Gets the value of the any property.
	 * 
	 * @return
	 *         possible object is {@link Object } {@link Element }
	 * 
	 */
	public Object getAny() {
		return any;
	}

	/**
	 * Sets the value of the any property.
	 * 
	 * @param value
	 *            allowed object is {@link Object } {@link Element }
	 * 
	 */
	public void setAny(Object value) {
		this.any = value;
	}

}
