//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * A service request consists of a single mandatory member denoting the security context of the caller, followed by one
 * of transaction, enquiry or routine request elements. OFSML 1.1 model groups are NOT permitted.
 * 
 * 
 * <p>
 * Java class for ofsml13ServiceRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ofsml13ServiceRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="securityContext" type="{http://www.temenos.com/T24/OFSML/130}ofsml13SecurityContext"/>
 *         &lt;group ref="{http://www.temenos.com/T24/OFSML/130}ofsml13ServiceRequestGroup"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ofsml13ServiceRequest", propOrder = { "securityContext", "ofsTransactionInput",
		"ofsTransactionAuthorise", "ofsTransactionSee", "ofsTransactionReverse", "ofsTransactionDelete",
		"ofsStandardEnquiry", "ofsExtendedEnquiry", "ofsStandardRoutine", "ofsXMLRoutine" })
public class Ofsml13ServiceRequest {

	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130", nillable = true)
	protected Ofsml13SecurityContext securityContext;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionInputRequest ofsTransactionInput;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionNonInputRequest ofsTransactionAuthorise;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionNonInputRequest ofsTransactionSee;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionNonInputRequest ofsTransactionReverse;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13TransactionNonInputRequest ofsTransactionDelete;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13EnquiryRequest ofsStandardEnquiry;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13EnquiryRequest ofsExtendedEnquiry;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13StandardRoutine ofsStandardRoutine;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13XMLRoutine ofsXMLRoutine;

	/**
	 * Gets the value of the securityContext property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13SecurityContext }
	 * 
	 */
	public Ofsml13SecurityContext getSecurityContext() {
		return securityContext;
	}

	/**
	 * Sets the value of the securityContext property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13SecurityContext }
	 * 
	 */
	public void setSecurityContext(Ofsml13SecurityContext value) {
		this.securityContext = value;
	}

	/**
	 * Gets the value of the ofsTransactionInput property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionInputRequest }
	 * 
	 */
	public Ofsml13TransactionInputRequest getOfsTransactionInput() {
		return ofsTransactionInput;
	}

	/**
	 * Sets the value of the ofsTransactionInput property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionInputRequest }
	 * 
	 */
	public void setOfsTransactionInput(Ofsml13TransactionInputRequest value) {
		this.ofsTransactionInput = value;
	}

	/**
	 * Gets the value of the ofsTransactionAuthorise property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public Ofsml13TransactionNonInputRequest getOfsTransactionAuthorise() {
		return ofsTransactionAuthorise;
	}

	/**
	 * Sets the value of the ofsTransactionAuthorise property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public void setOfsTransactionAuthorise(Ofsml13TransactionNonInputRequest value) {
		this.ofsTransactionAuthorise = value;
	}

	/**
	 * Gets the value of the ofsTransactionSee property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public Ofsml13TransactionNonInputRequest getOfsTransactionSee() {
		return ofsTransactionSee;
	}

	/**
	 * Sets the value of the ofsTransactionSee property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public void setOfsTransactionSee(Ofsml13TransactionNonInputRequest value) {
		this.ofsTransactionSee = value;
	}

	/**
	 * Gets the value of the ofsTransactionReverse property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public Ofsml13TransactionNonInputRequest getOfsTransactionReverse() {
		return ofsTransactionReverse;
	}

	/**
	 * Sets the value of the ofsTransactionReverse property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public void setOfsTransactionReverse(Ofsml13TransactionNonInputRequest value) {
		this.ofsTransactionReverse = value;
	}

	/**
	 * Gets the value of the ofsTransactionDelete property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public Ofsml13TransactionNonInputRequest getOfsTransactionDelete() {
		return ofsTransactionDelete;
	}

	/**
	 * Sets the value of the ofsTransactionDelete property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13TransactionNonInputRequest }
	 * 
	 */
	public void setOfsTransactionDelete(Ofsml13TransactionNonInputRequest value) {
		this.ofsTransactionDelete = value;
	}

	/**
	 * Gets the value of the ofsStandardEnquiry property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13EnquiryRequest }
	 * 
	 */
	public Ofsml13EnquiryRequest getOfsStandardEnquiry() {
		return ofsStandardEnquiry;
	}

	/**
	 * Sets the value of the ofsStandardEnquiry property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13EnquiryRequest }
	 * 
	 */
	public void setOfsStandardEnquiry(Ofsml13EnquiryRequest value) {
		this.ofsStandardEnquiry = value;
	}

	/**
	 * Gets the value of the ofsExtendedEnquiry property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13EnquiryRequest }
	 * 
	 */
	public Ofsml13EnquiryRequest getOfsExtendedEnquiry() {
		return ofsExtendedEnquiry;
	}

	/**
	 * Sets the value of the ofsExtendedEnquiry property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13EnquiryRequest }
	 * 
	 */
	public void setOfsExtendedEnquiry(Ofsml13EnquiryRequest value) {
		this.ofsExtendedEnquiry = value;
	}

	/**
	 * Gets the value of the ofsStandardRoutine property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13StandardRoutine }
	 * 
	 */
	public Ofsml13StandardRoutine getOfsStandardRoutine() {
		return ofsStandardRoutine;
	}

	/**
	 * Sets the value of the ofsStandardRoutine property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13StandardRoutine }
	 * 
	 */
	public void setOfsStandardRoutine(Ofsml13StandardRoutine value) {
		this.ofsStandardRoutine = value;
	}

	/**
	 * Gets the value of the ofsXMLRoutine property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13XMLRoutine }
	 * 
	 */
	public Ofsml13XMLRoutine getOfsXMLRoutine() {
		return ofsXMLRoutine;
	}

	/**
	 * Sets the value of the ofsXMLRoutine property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13XMLRoutine }
	 * 
	 */
	public void setOfsXMLRoutine(Ofsml13XMLRoutine value) {
		this.ofsXMLRoutine = value;
	}

}
