//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.temenos.com/T24/OFSML/130")
package com.temenos.messagingLayer.pojo;

