//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 * The 'T24' element is the ROOT element of the OFSML Schema.
 * The element has optional members: ofsmlHeader, requestProcessing, responseProcessing. The element has
 * mandatory members: one of either serviceRequest (input message) or serviceResponse (output message).
 * For all members (and children of members), limited use of nil elements may be used to denote optional elements
 * (or that will be defaulted inside the application) to allow explicit use of verbose OFSML instance productions for
 * clarity
 * where required.
 * All headers are optional. Specifying a header element (with child elements or 'nil' content) forces the TEMENOS Open
 * Connectivity
 * Framework (TOCF) to attempt to construct the headers in full on the response. The ofsmlHeader element is used by the
 * TOCF to
 * provide message identity and to add some extended information such as time stamps. The requestProcessing element
 * defines
 * the handling properties of a request message and the responseProcessing element the handling of the corresponding
 * response.
 * These optional elements are followed by either a service request (inbound), corresponding response (outbound), or a
 * serviceSend
 * (one-way outbound) where a serviceRequest element is an OFS transaction (application/version), OFS enquiry or an OFS
 * routine
 * request, a serviceResponse element is the corresponding response and a serviceSend element is an ofsEvent. An OFS
 * fault may
 * be substituted in the serviceResponse or serviceSend the elements, indicating a failure to process the message. Note
 * some elements
 * of the ofsmlHeader and requestProcessing elements are not intended for direct use by the caller (at sending time),
 * but will be returned
 * completed by the system should the caller specify an empty (nil) element tag for either of these elements.
 * 
 * 
 * <p>
 * Java class for T24 element declaration.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="T24">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="ofsmlHeader" type="{http://www.temenos.com/T24/OFSML/130}ofsml13Header" minOccurs="0"/>
 *           &lt;element name="requestProcessing" type="{http://www.temenos.com/T24/OFSML/130}ofsml13RequestProcessing" minOccurs="0"/>
 *           &lt;element name="responseProcessing" type="{http://www.temenos.com/T24/OFSML/130}ofsml13ResponseProcessing" minOccurs="0"/>
 *           &lt;choice>
 *             &lt;element name="serviceRequest" type="{http://www.temenos.com/T24/OFSML/130}ofsml13ServiceRequest"/>
 *             &lt;element name="serviceResponse" type="{http://www.temenos.com/T24/OFSML/130}ofsml13ServiceResponse"/>
 *             &lt;element name="serviceSend" type="{http://www.temenos.com/T24/OFSML/130}ofsml13ServiceSend"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *         &lt;attribute name="signature" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "ofsmlHeader", "requestProcessing", "responseProcessing", "serviceRequest",
		"serviceResponse", "serviceSend" })
@XmlRootElement(name = "T24")
public class T24 {

	@XmlElementRef(name = "ofsmlHeader", namespace = "http://www.temenos.com/T24/OFSML/130", type = JAXBElement.class)
	protected JAXBElement<Ofsml13Header> ofsmlHeader;
	@XmlElementRef(name = "requestProcessing", namespace = "http://www.temenos.com/T24/OFSML/130", type = JAXBElement.class)
	protected JAXBElement<Ofsml13RequestProcessing> requestProcessing;
	@XmlElementRef(name = "responseProcessing", namespace = "http://www.temenos.com/T24/OFSML/130", type = JAXBElement.class)
	protected JAXBElement<Ofsml13ResponseProcessing> responseProcessing;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13ServiceRequest serviceRequest;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13ServiceResponse serviceResponse;
	@XmlElement(namespace = "http://www.temenos.com/T24/OFSML/130")
	protected Ofsml13ServiceSend serviceSend;
	@XmlAttribute
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String signature;

	/**
	 * Gets the value of the ofsmlHeader property.
	 * 
	 * @return
	 *         possible object is {@link JAXBElement }{@code <}{@link Ofsml13Header }{@code >}
	 * 
	 */
	public JAXBElement<Ofsml13Header> getOfsmlHeader() {
		return ofsmlHeader;
	}

	/**
	 * Sets the value of the ofsmlHeader property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link Ofsml13Header }{@code >}
	 * 
	 */
	public void setOfsmlHeader(JAXBElement<Ofsml13Header> value) {
		this.ofsmlHeader = ((JAXBElement<Ofsml13Header>) value);
	}

	/**
	 * Gets the value of the requestProcessing property.
	 * 
	 * @return
	 *         possible object is {@link JAXBElement }{@code <}{@link Ofsml13RequestProcessing }{@code >}
	 * 
	 */
	public JAXBElement<Ofsml13RequestProcessing> getRequestProcessing() {
		return requestProcessing;
	}

	/**
	 * Sets the value of the requestProcessing property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link Ofsml13RequestProcessing }{@code >}
	 * 
	 */
	public void setRequestProcessing(JAXBElement<Ofsml13RequestProcessing> value) {
		this.requestProcessing = ((JAXBElement<Ofsml13RequestProcessing>) value);
	}

	/**
	 * Gets the value of the responseProcessing property.
	 * 
	 * @return
	 *         possible object is {@link JAXBElement }{@code <}{@link Ofsml13ResponseProcessing }{@code >}
	 * 
	 */
	public JAXBElement<Ofsml13ResponseProcessing> getResponseProcessing() {
		return responseProcessing;
	}

	/**
	 * Sets the value of the responseProcessing property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link Ofsml13ResponseProcessing }{@code >}
	 * 
	 */
	public void setResponseProcessing(JAXBElement<Ofsml13ResponseProcessing> value) {
		this.responseProcessing = ((JAXBElement<Ofsml13ResponseProcessing>) value);
	}

	/**
	 * Gets the value of the serviceRequest property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13ServiceRequest }
	 * 
	 */
	public Ofsml13ServiceRequest getServiceRequest() {
		return serviceRequest;
	}

	/**
	 * Sets the value of the serviceRequest property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13ServiceRequest }
	 * 
	 */
	public void setServiceRequest(Ofsml13ServiceRequest value) {
		this.serviceRequest = value;
	}

	/**
	 * Gets the value of the serviceResponse property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13ServiceResponse }
	 * 
	 */
	public Ofsml13ServiceResponse getServiceResponse() {
		return serviceResponse;
	}

	/**
	 * Sets the value of the serviceResponse property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13ServiceResponse }
	 * 
	 */
	public void setServiceResponse(Ofsml13ServiceResponse value) {
		this.serviceResponse = value;
	}

	/**
	 * Gets the value of the serviceSend property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13ServiceSend }
	 * 
	 */
	public Ofsml13ServiceSend getServiceSend() {
		return serviceSend;
	}

	/**
	 * Sets the value of the serviceSend property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13ServiceSend }
	 * 
	 */
	public void setServiceSend(Ofsml13ServiceSend value) {
		this.serviceSend = value;
	}

	/**
	 * Gets the value of the signature property.
	 * 
	 * @return
	 *         possible object is {@link String }
	 * 
	 */
	public String getSignature() {
		return signature;
	}

	/**
	 * Sets the value of the signature property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSignature(String value) {
		this.signature = value;
	}

}
