//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.20 at 02:21:10 PM IST 
//

package com.temenos.messagingLayer.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.w3c.dom.Element;

/**
 * 
 * This element is for use in custom routines that accept and return XML ONLY. Custom routines that accept and return
 * parameters as XML must use this element definition for their response.
 * This is intended for routines that generate an XML document fragment. In the event of an error in processing, a
 * routine should return error details using the sequence of 'ofsFault' elements with the error flagged by the status
 * attribute on this model group. In an error condition, the ofsFault elements returned from the routine are mapped to
 * the
 * main error handling features of OFSML. In a normal processing condition (no error), the content (note: only the
 * content)
 * of the T24RoutineResponse element is returned in the body of the OFSML ofsRoutineResponse element (i.e. without the
 * T24RoutineResponse tags). In an exceptional processing condition (error), the ofsFault tags are mapped to the main
 * OFSML
 * response document including (if supplied) the ofsFaultDetails. If ofsFaultDetails are not supplied, the standard
 * ofsFault details
 * (the original request) will be inserted.
 * Note that the request and (normal) response document fragment from a routine generating XML is restricted to a single
 * root tag
 * for the document fragment. This root tag, which must not be a definition from the OFSML namespace, should be defined
 * as the
 * root tag in the extension Schema.
 * 
 * 
 * <p>
 * Java class for T24RoutineResponse element declaration.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="T24RoutineResponse">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;choice>
 *           &lt;any/>
 *           &lt;group ref="{http://www.temenos.com/T24/OFSML/130}ofsml13FaultGroup"/>
 *         &lt;/choice>
 *         &lt;attribute name="status" use="required" type="{http://www.temenos.com/T24/OFSML/130}ofsml13RoutineStatus" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "content" })
@XmlRootElement(name = "T24RoutineResponse")
public class T24RoutineResponse {

	@XmlElementRefs({
			@XmlElementRef(name = "ofsFaultCode", namespace = "http://www.temenos.com/T24/OFSML/130", type = JAXBElement.class),
			@XmlElementRef(name = "ofsFaultDetails", namespace = "http://www.temenos.com/T24/OFSML/130", type = JAXBElement.class),
			@XmlElementRef(name = "ofsFaultContext", namespace = "http://www.temenos.com/T24/OFSML/130", type = JAXBElement.class),
			@XmlElementRef(name = "ofsFaultMessage", namespace = "http://www.temenos.com/T24/OFSML/130", type = JAXBElement.class) })
	@XmlMixed
	@XmlAnyElement(lax = true)
	protected List<Object> content;
	@XmlAttribute(required = true)
	protected Ofsml13RoutineStatus status;

	/**
	 * Gets the value of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}{@link Ofsml13FaultDetails }
	 * {@code >} {@link JAXBElement }{@code <}{@link Ofsml13FaultCode }{@code >} {@link JAXBElement }{@code <}
	 * {@link String }{@code >} {@link Object } {@link JAXBElement }{@code <}{@link Ofsml13FaultMessage }{@code >}
	 * {@link String } {@link Element }
	 * 
	 * 
	 */
	public List<Object> getContent() {
		if (content == null) {
			content = new ArrayList<Object>();
		}
		return this.content;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return
	 *         possible object is {@link Ofsml13RoutineStatus }
	 * 
	 */
	public Ofsml13RoutineStatus getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *            allowed object is {@link Ofsml13RoutineStatus }
	 * 
	 */
	public void setStatus(Ofsml13RoutineStatus value) {
		this.status = value;
	}

}
