package com.temenos.ebank.domain;

// Generated 6 janv. 2011 09:56:01 by Hibernate Tools 3.4.0.Beta1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private static final long serialVersionUID = -8383547227585000671L;

	private Long adrId;
	private String country;
	private String line1;
	private String line2;
	private String county;
	private String district;
	private String town;
	private String postcode;

	public Address() {
	}

	public Address(Long adrId, String country) {
		this.adrId = adrId;
		this.country = country;
	}

	public Address(Long adrId, String country, String line1, String line2, String county, String district, String town, String postcode) {
		this.adrId = adrId;
		this.country = country;
		this.line1 = line1;
		this.line2 = line2;
		this.county = county;
		this.district = district;
		this.town = town;
		this.postcode = postcode;
	}

	public Long getAdrId() {
		return this.adrId;
	}

	public void setAdrId(Long adrId) {
		this.adrId = adrId;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getLine1() {
		return this.line1;
	}

	public void setLine1(String line1) {
		this.line1 = line1;
	}

	public String getLine2() {
		return this.line2;
	}

	public void setLine2(String line2) {
		this.line2 = line2;
	}

	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getCounty() {
		return county;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getDistrict() {
		return district;
	}

}
