package com.temenos.ebank.domain;

// Generated 6 janv. 2011 09:56:01 by Hibernate Tools 3.4.0.Beta1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.StringUtils;

import com.temenos.ebank.domain.util.ComposedFieldHelper;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Long custId;
	private Long appId;
	private String title;
	private String firstName;
	private String lastName;
	private String previousName;
	private String motherMaidenName;
	private Date dateOfBirth;
	private String gender = "M";
	private String maritalStatus;
	private String nationality;
	private String townOfBirth;
	private String countryOfBirth;
	private String mobilePhone;
	private String homePhone;
	private String workPhone;
	private String faxNumber;
	private String emailAddress;
	private String jointRelationship;
	private Boolean isExistingCustomer;
	private String existingAccNumber;
	private String existingIban;
	private String existingBic;
	private String existingSortCode;
	private String countryResidence;
	private String countryMoving;
	private String preferredContactMethod;
	private String residentialStatus;
	private String otherResidentialStatus;
	private BigDecimal residentialAdrId;
	private Integer residentialAdrPeriod;
	private BigDecimal correspondenceAdrId;
	private String adrTypeForDebitCard;
	private String employmentStatus;
	private String occupation;
	private String employerName;
	private Long employerAdrId;
	private Integer employmentLastDuration;
	private Boolean flagReceiveMarketing = false;
	private List<String> marketingContactMethods;
	private Boolean flagDiscloseIdentity = false;

	private Address residentialAddress;
	private PreviousAddress[] previousAddresses;
	private Address correspondenceAddress;

	private Address employerAddress;

	
	
	private Boolean isCorrespondenceAddressSameAsResidential = true;

	public Customer() {
	}

	public Customer(Long custId, Long appId) {
		this.custId = custId;
		this.appId = appId;
	}

	public Long getCustId() {
		return this.custId;
	}

	public void setCustId(Long custId) {
		this.custId = custId;
	}

	public Long getAppId() {
		return this.appId;
	}

	public void setAppId(Long appId) {
		this.appId = appId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPreviousName() {
		return this.previousName;
	}

	public void setPreviousName(String previousName) {
		this.previousName = previousName;
	}

	public String getMotherMaidenName() {
		return this.motherMaidenName;
	}

	public void setMotherMaidenName(String motherMaidenName) {
		this.motherMaidenName = motherMaidenName;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getTownOfBirth() {
		return this.townOfBirth;
	}

	public void setTownOfBirth(String townOfBirth) {
		this.townOfBirth = townOfBirth;
	}

	public String getCountryOfBirth() {
		return this.countryOfBirth;
	}

	public void setCountryOfBirth(String countryOfBirth) {
		this.countryOfBirth = countryOfBirth;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	public String getWorkPhone() {
		return this.workPhone;
	}

	public void setWorkPhone(String workPhone) {
		this.workPhone = workPhone;
	}

	public String getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getJointRelationship() {
		return this.jointRelationship;
	}

	public void setJointRelationship(String jointRelationship) {
		this.jointRelationship = jointRelationship;
	}

	public Boolean getIsExistingCustomer() {
		return this.isExistingCustomer;
	}

	public void setIsExistingCustomer(Boolean isExistingCustomer) {
		this.isExistingCustomer = isExistingCustomer;
	}

	public String getExistingAccNumber() {
		return this.existingAccNumber;
	}

	public void setExistingAccNumber(String existingAccNumber) {
		this.existingAccNumber = existingAccNumber;
	}

	public String getExistingIban() {
		return this.existingIban;
	}

	public void setExistingIban(String existingIban) {
		this.existingIban = existingIban;
	}

	public String getExistingBic() {
		return existingBic;
	}

	public void setExistingBic(String existingBic) {
		this.existingBic = existingBic;
	}

	public String getExistingSortCode() {
		return this.existingSortCode;
	}

	public void setExistingSortCode(String existingSortCode) {
		this.existingSortCode = existingSortCode;
	}

	public String getCountryResidence() {
		return this.countryResidence;
	}

	public void setCountryResidence(String countryResidence) {
		this.countryResidence = countryResidence;
	}

	public String getCountryMoving() {
		return this.countryMoving;
	}

	public void setCountryMoving(String countryMoving) {
		this.countryMoving = countryMoving;
	}

	public String getPreferredContactMethod() {
		return this.preferredContactMethod;
	}

	public void setPreferredContactMethod(String preferredContactMethod) {
		this.preferredContactMethod = preferredContactMethod;
	}

	public String getResidentialStatus() {
		return this.residentialStatus;
	}

	public void setResidentialStatus(String residentialStatus) {
		this.residentialStatus = residentialStatus;
	}

	public BigDecimal getResidentialAdrId() {
		return this.residentialAdrId;
	}

	public void setResidentialAdrId(BigDecimal residentialAdrId) {
		this.residentialAdrId = residentialAdrId;
	}

	public Integer getResidentialAdrPeriod() {
		return this.residentialAdrPeriod;
	}

	public void setResidentialAdrPeriod(Integer residentialAdrPeriod) {
		this.residentialAdrPeriod = residentialAdrPeriod;
	}

	public BigDecimal getCorrespondenceAdrId() {
		return this.correspondenceAdrId;
	}

	public void setCorrespondenceAdrId(BigDecimal correspondenceAdrId) {
		this.correspondenceAdrId = correspondenceAdrId;
	}

	public String getAdrTypeForDebitCard() {
		return this.adrTypeForDebitCard;
	}

	public void setAdrTypeForDebitCard(String adrTypeForDebitCard) {
		this.adrTypeForDebitCard = adrTypeForDebitCard;
	}

	public String getEmploymentStatus() {
		return this.employmentStatus;
	}

	public void setEmploymentStatus(String employmentStatus) {
		this.employmentStatus = employmentStatus;
	}

	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getEmployerName() {
		return this.employerName;
	}

	public void setEmployerName(String employerName) {
		this.employerName = employerName;
	}

	public Long getEmployerAdrId() {
		return this.employerAdrId;
	}

	public void setEmployerAdrId(Long employerAdrId) {
		this.employerAdrId = employerAdrId;
	}

	public Integer getEmploymentLastDuration() {
		return this.employmentLastDuration;
	}

	public void setEmploymentLastDuration(Integer employmentLastDuration) {
		this.employmentLastDuration = employmentLastDuration;
	}

	public Boolean getFlagReceiveMarketing() {
		return this.flagReceiveMarketing;
	}

	public void setFlagReceiveMarketing(Boolean flagReceiveMarketing) {
		this.flagReceiveMarketing = flagReceiveMarketing;
	}

	public String getMarketingContactMethod() {
		return ComposedFieldHelper.getFieldWithSeparators(marketingContactMethods, ";");
	}

	public void setMarketingContactMethod(String marketingContactMethod) {
		this.marketingContactMethods = new ArrayList<String>();
		if (StringUtils.isNotBlank(marketingContactMethod)) {
			this.marketingContactMethods = ComposedFieldHelper.splitField(marketingContactMethod, ";");
		}
	}

	public List<String> getMarketingContactMethods() {
		return marketingContactMethods;
	}

	public void setMarketingContactMethods(List<String> marketingContactMethods) {
		this.marketingContactMethods = marketingContactMethods;
	}
	
	public Address getEmployerAddress() {
		return employerAddress;
	}

	public void setEmployerAddress(Address employmentAddress) {
		this.employerAddress = employmentAddress;
	}

	public void setOtherResidentialStatus(String otherResidentialStatus) {
		this.otherResidentialStatus = otherResidentialStatus;
	}

	public String getOtherResidentialStatus() {
		return otherResidentialStatus;
	}

	public void setResidentialAddress(Address residentialAddress) {
		this.residentialAddress = residentialAddress;
	}

	public Address getResidentialAddress() {
		return residentialAddress;
	}

	public void setCorrespondenceAddress(Address correspondenceAddress) {
		this.correspondenceAddress = correspondenceAddress;
	}

	public Address getCorrespondenceAddress() {
		return correspondenceAddress;
	}

	public void setPreviousAddresses(PreviousAddress[] previousAddresses) {
		this.previousAddresses = previousAddresses;
	}

	public PreviousAddress[] getPreviousAddresses() {
		return previousAddresses;
	}

	public Boolean getFlagDiscloseIdentity() {
		return flagDiscloseIdentity;
	}

	public void setFlagDiscloseIdentity(Boolean flagDiscloseIdentity) {
		this.flagDiscloseIdentity = flagDiscloseIdentity;
	}

	public void setOtherEmploymentStatus(String otherEmploymentStatus) {
		setOccupation(otherEmploymentStatus);
	}

	public String getOtherEmploymentStatus() {
		return getOccupation();
	}


	public void setIsCorrespondenceAddressSameAsResidential(Boolean isCorrespondenceAddressSameAsResidential) {
		this.isCorrespondenceAddressSameAsResidential = isCorrespondenceAddressSameAsResidential;
	}

	public Boolean getIsCorrespondenceAddressSameAsResidential() {
		return isCorrespondenceAddressSameAsResidential;
	}

}
