#
# Populate your responder inmemory database with some test values
#
# For example:
INSERT INTO `Address`(`id` , `country` , `line1` , `line2` , `county` , `district` , `town` , `postcode`) VALUES('1' , 'UK' , 'Maylands Avenue' , '' , 'Hertfordshire' , 'Dacorum' , 'Hemel Hempstead' , 'HP2 4NW');	
INSERT INTO `Address`(`id` , `country` , `line1` , `line2` , `county` , `district` , `town` , `postcode`) VALUES('2' , 'CH' , 'Rue temenos' , '' , 'Geneva' , '' , 'Geneva' , '2548');	
INSERT INTO `Country`(`code` , `languageCode` , `label`) VALUES('UK' , 'en' , 'United Kingdom');	
INSERT INTO `Country`(`code` , `languageCode` , `label`) VALUES('CH' , 'de' , 'Switzerland');	

INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('118','en','ftdTerm','6','6 months','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('119','en','ftdTerm','12','1 year','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('120','en','ftdTerm','24','2 years','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('121','en','ftdTerm','36','3 years','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('122','en','ftdTerm','60','5 years','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('123','en','interestPayment','MONTHLY_ROLLOVER','Monthly - Rollover deposit amount only','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('124','en','interestPayment','MONTHLY_NO_ROLLOVER','Monthly - No Rollover','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('125','en','interestPayment','ANNUAL_ROLLOVER','Annual - Rollover deposit amount only','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('126','en','interestPayment','ANNUAL_NO_ROLLOVER','Annual - No Rollover','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('127','en','interestPayment','MATURITY_ROLLOVER','At Maturity - Rollover deposit amount','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('128','en','interestPayment','MATURITY_INTEREST','At Maturity - Rollover deposit amount + interest','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('129','en','interestPayment','MATURITY_NO_ROLLOVER','At Maturity - No Rollover','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('130','en','marketingContactChoice','HOME_PHONE','Home Phone','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('131','en','marketingContactChoice','WORK_PHONE','Work phone','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('132','en','marketingContactChoice','MOBILE','Mobile','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('133','en','marketingContactChoice','EMAIL','Email','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('134','en','postAddressType','RESIDENT','Resident','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('135','en','postAddressType','CORRESPONDENCE','Correspondence','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('12','en','title','MS','Ms','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('13','en','title','DR','Dr','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('14','en','title','OTHER','Other','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('15','en','maritalStatus','M','Married','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('16','en','maritalStatus','S','Single','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('17','en','maritalStatus','U','Unmarried partners','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('37','en','residentialStatus','PARENTS','Living with parents','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('38','en','residentialStatus','OTHER','Other','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('39','en','employmentStatus','EMPLOYED','Employed','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('40','en','employmentStatus','SELF','Self-employed','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('41','en','employmentStatus','RETIRED','Retired','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('42','en','employmentStatus','HOUSE','Housewife / Husband','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('43','en','employmentStatus','OTHER','Other','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('44','en','establishmentReason','SALARY','Salary','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('45','en','establishmentReason','PAYMENTS','Payments','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('46','en','establishmentReason','BANKING','Day-to-day Banking','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('47','en','establishmentReason','TRAVELLING','Travelling on business','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('48','en','establishmentReason','OTHER','Other','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('49','en','usageReason','BANKING','Day to day banking needs','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('50','en','usageReason','MULTI_ACCOUNTS','Multi currency accounts and cards to facilitate international travel','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('51','en','usageReason','RETIREMENT','Saving for retirement','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('52','en','usageReason','HOUSE_PURCHASE','Saving for house purchase','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('53','en','usageReason','CHILDREN_EDUCATION','Saving for children education','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('54','en','usageReason','LIFE_EVENT','Saving for a Life Event','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('55','en','usageReason','OTHER','Other','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('56','en','annualDeposit','UNDER_1000','Under £ 1,000','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('57','en','annualDeposit','BETWEEN_1000_10000','£ 1,000-£ 10,000','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('58','en','annualDeposit','OVER_10000','£ 10,000 and over','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('59','en','activityOrigin','OWN_ACCOUNT','From own bank account','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('73','en','activityWealth','BUSINESS_MANAGEMENT','Managing your own business','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('74','en','activityWealth','INHERITANCE','Inheriting family wealth','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('75','en','activityWealth','OTHER','Other','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('76','en','hearSource','WEBSITE','Website','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('77','en','hearSource','SEARCH_ENGINE','Search engine','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('78','en','hearSource','ONLINE_ADVERT','Online advert','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('79','en','hearSource','RECOMMENDATION','Recommendation from existing customer','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('80','en','hearSource','ADVERTISING','Advertising','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('81','en','hearSource','BRANCH','Lloyds TSB branch','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('1','en','COUNTRY','GB','United Kingdom','1');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('2','en','COUNTRY','US','United States','3');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('3','en','NATIONALITY','GB','British','1');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('4','en','NATIONALITY','US','American','2');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('5','en','COUNTRY','UAE','United Arab Emirates','2');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('9','en','title','MR','Mr','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('10','en','title','MISS','Miss','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('11','en','title','MRS','Mrs','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('18','en','maritalStatus','D','Divorced','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('19','en','maritalStatus','W','Widow','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('20','en','jointRelationship','SPOUSE','Spouse','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('21','en','jointRelationship','SON','Son','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('22','en','jointRelationship','DAUGHTER','Daughter','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('23','en','annualIncome','49999','Under £ 50,000','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('24','en','annualIncome','50000','£ 50,000 and over','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('25','en','estimatedDepositAmount','24999','Under £ 25,000','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('26','en','estimatedDepositAmount','99999','£ 25,000-£ 99,000','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('27','en','estimatedDepositAmount','100000','£ 100,000 and over','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('28','en','contactChoice','NO_PREF','No preference','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('29','en','contactChoice','HOME_PHONE','Home Phone','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('30','en','contactChoice','WORK_PHONE','Work phone','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('31','en','contactChoice','MOBILE','Mobile','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('32','en','contactChoice','EMAIL','Email','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('33','en','residentialStatus','OWNER_NO_MORTGAGE','Owner - no mortgage ','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('34','en','residentialStatus','OWNER_MORTGAGE','Owner - mortgage','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('35','en','residentialStatus','TENNANT_LOCAL','Tennant - local authority','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('36','en','residentialStatus','TENANT_PRIVATE','Tenant - private','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('60','en','activityOrigin','SALARY','Salary/Bonus','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('61','en','activityOrigin','REDUNDANCY','Redundancy','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('62','en','activityOrigin','SOLICITOR','From Solicitor','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('63','en','activityOrigin','BROKER','From Broker','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('64','en','activityOrigin','FAMILY','From spouse/other family members','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('65','en','activityOrigin','INSURANCE_COMPANY','From Insurance company','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('66','en','activityOrigin','LOTTERY','Lottery winnings','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('67','en','activityOrigin','GAMBLING','Gambling winning','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('68','en','activityOrigin','TRUST','Trust Settlement','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('69','en','activityOrigin','GIFT','Gift','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('70','en','activityOrigin','LOAN','Loan','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('71','en','activityOrigin','OTHER','Other','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('72','en','activityWealth','LIFETIME_SAVINGS','Earnings during your lifetime','0');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('6','en','COUNTRY','JP','Japan','4');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('82','en','CA.accountCurrency','GBP','Sterling','1');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('83','en','CA.accountCurrency','EUR','Euro','2');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('84','en','CA.accountCurrency','USD','US Dollar','3');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('85','en','RS.accountCurrency','GBP','Sterling','1');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('86','en','RS.accountCurrency','EUR','Euro','2');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('87','en','RS.accountCurrency','USD','US Dollar','3');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('88','en','IASA.accountCurrency','GBP','Sterling','1');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('89','en','IASA.accountCurrency','EUR','Euro','2');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('90','en','IASA.accountCurrency','USD','US Dollar','3');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('91','en','IASA.accountCurrency','HKD','HK $','4');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('92','en','IASA.accountCurrency','CAN','CAN $','5');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('93','en','IASA.accountCurrency','AUS','AUS $','6');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('94','en','IASA.accountCurrency','NZD','NZ $','7');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('95','en','IASA.accountCurrency','YEN','Yen','8');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('96','en','IASA.accountCurrency','SGD','Sing $','9');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('97','en','IASA.accountCurrency','CHF','CHF','10');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('98','en','IBSA.accountCurrency','GBP','Sterling','1');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('99','en','IBSA.accountCurrency','EUR','Euro','2');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('100','en','IBSA.accountCurrency','USD','US Dollar','3');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('101','en','IBSA.accountCurrency','HKD','HK $','4');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('102','en','IBSA.accountCurrency','CAN','CAN $','5');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('103','en','RASA.accountCurrency','GBP','Sterling','1');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('104','en','RASA.accountCurrency','EUR','Euro','2');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('105','en','RASA.accountCurrency','USD','US Dollar','3');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('106','en','RASA.accountCurrency','HKD','HK $','4');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('107','en','RASA.accountCurrency','CAN','CAN $','5');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('108','en','FTD.accountCurrency','GBP','Sterling','1');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('109','en','FTD.accountCurrency','EUR','Euro','2');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('110','en','FTD.accountCurrency','USD','US Dollar','3');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('111','en','FTD.accountCurrency','HKD','HK $','4');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('112','en','FTD.accountCurrency','CAN','CAN $','5');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('113','en','FTD.accountCurrency','AUS','AUS $','6');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('114','en','FTD.accountCurrency','NZD','NZ $','7');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('115','en','FTD.accountCurrency','YEN','Yen','8');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('116','en','FTD.accountCurrency','SGD','Sing $','9');
INSERT INTO `Nomencl`(`id` , `language` , `groupCode` , `code` , `label` , `sortOrder`) VALUES('117','en','FTD.accountCurrency','CHF','CHF','10');
