//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.29 at 07:48:51 PM IST 
//

package com.temenos.messagingLayer.mappingpojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _T24Field_QNAME = new QName("", "T24field");
	private final static QName _FrontEndObject_QNAME = new QName("", "FrontEndObject");
	private final static QName _T24Value_QNAME = new QName("", "T24Value");
	private final static QName _Operation_QNAME = new QName("", "operation");
	private final static QName _Application_QNAME = new QName("", "application");
	private final static QName _Version_QNAME = new QName("", "version");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * generated
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Group }
	 * 
	 */
	public Group createGroup() {
		return new Group();
	}

	/**
	 * Create an instance of {@link T24Constant }
	 * 
	 */
	public T24Constant createT24Constant() {
		return new T24Constant();
	}

	/**
	 * Create an instance of {@link FieldMapping }
	 * 
	 */
	public FieldMapping createFieldMapping() {
		return new FieldMapping();
	}

	/**
	 * Create an instance of {@link T24 }
	 * 
	 */
	public T24 createT24() {
		return new T24();
	}

	/**
	 * Create an instance of {@link Step }
	 * 
	 */
	public Step createStep() {
		return new Step();
	}

	/**
	 * Create an instance of {@link Applicant }
	 * 
	 */
	public Applicant createApplicant() {
		return new Applicant();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "T24field")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	public JAXBElement<String> createT24Field(String value) {
		return new JAXBElement<String>(_T24Field_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "FrontEndObject")
	public JAXBElement<String> createFrontEndObject(String value) {
		return new JAXBElement<String>(_FrontEndObject_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "T24Value")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	public JAXBElement<String> createT24Value(String value) {
		return new JAXBElement<String>(_T24Value_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "operation")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	public JAXBElement<String> createOperation(String value) {
		return new JAXBElement<String>(_Operation_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "application")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	public JAXBElement<String> createApplication(String value) {
		return new JAXBElement<String>(_Application_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "version")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	public JAXBElement<String> createVersion(String value) {
		return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
	}

}
