/*
 * generated by Xtext
 */
package com.temenos.interaction.rimdsl;

import org.eclipse.xtext.generator.IGenerator;

import com.temenos.interaction.rimdsl.generator.RIMDslGeneratorSwagger;

/*
 * #%L
 * com.temenos.interaction.rimdsl.RimDsl - Grammar
 * %%
 * Copyright (C) 2012 - 2013 Temenos Holdings N.V.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RIMDslRuntimeModuleSwagger extends RIMDslRuntimeModule {

	public Class<? extends IGenerator> bindIGenerator() {
		return RIMDslGeneratorSwagger.class;
	}

	@Override
	public Class<? extends org.eclipse.xtext.resource.containers.IAllContainersState.Provider> bindIAllContainersState$Provider() {
		return FasterResourceSetBasedAllContainersStateProvider.class;
	}
}
